/** @type {import('next').NextConfig} */
const nextConfig = {
  compress: true,
  poweredByHeader: false,
  images: {
    formats: ["image/avif", "image/webp"],
    minimumCacheTTL: 31536000, // 1 year
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    remotePatterns: [
      { protocol: "https", hostname: "i.ytimg.com", pathname: "/vi/**" },
      { protocol: "https", hostname: "img.youtube.com", pathname: "/vi/**" },
      { protocol: "https", hostname: "desertrecoverycenters.com", pathname: "/wp-content/**" },
      { protocol: "https", hostname: "cdn.sanity.io" },
    ],
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "X-Content-Type-Options",
            value: "nosniff",
          },
          {
            key: "X-Frame-Options",
            value: "SAMEORIGIN",
          },
          {
            key: "Referrer-Policy",
            value: "strict-origin-when-cross-origin",
          },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(self), payment=()",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://challenges.cloudflare.com https://www.youtube.com https://s.ytimg.com https://cdn.livechatinc.com https://api.livechatinc.com https://*.tctm.co https://googleads.g.doubleclick.net",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "img-src 'self' data: https: blob:",
              "font-src 'self' https://fonts.gstatic.com data:",
              "connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://www.google.com https://api.desertrecoverycenters.com https://challenges.cloudflare.com https://api.livechatinc.com https://cdn.livechatinc.com wss://*.livechatinc.com https://*.tctm.co",
              "frame-src 'self' https://www.youtube.com https://www.youtube-nocookie.com https://challenges.cloudflare.com https://secure.livechatinc.com",
              "object-src 'none'",
              "base-uri 'self'",
              "form-action 'self'",
              "frame-ancestors 'self'",
              "upgrade-insecure-requests",
            ].join("; "),
          },
        ],
      },
    ];
  },
  async redirects() {
    return [
      // Deleted fake location pages → nearest real facility (East Valley → Phoenix PHP/IOP, NW Valley → Glendale, Scottsdale-area → Scottsdale)
      { source: "/locations/chandler", destination: "/locations/phoenix-php-iop", permanent: true },
      { source: "/locations/gilbert", destination: "/locations/phoenix-php-iop", permanent: true },
      { source: "/locations/mesa", destination: "/locations/phoenix-php-iop", permanent: true },
      { source: "/locations/tempe", destination: "/locations/phoenix-php-iop", permanent: true },
      // /locations/phoenix legacy URL → real outpatient facility
      { source: "/locations/phoenix", destination: "/locations/phoenix-php-iop", permanent: true },
      { source: "/locations/surprise", destination: "/locations/glendale", permanent: true },
      { source: "/locations/peoria", destination: "/locations/glendale", permanent: true },
      { source: "/locations/north-scottsdale", destination: "/locations/scottsdale", permanent: true },
      { source: "/locations/paradise-valley", destination: "/locations/scottsdale", permanent: true },
      // Old broken paths fixed in href audit
      { source: "/about/luxury-vs-standard", destination: "/resources/luxury-vs-standard-rehab", permanent: true },
      { source: "/about/our-team", destination: "/our-team", permanent: true },
      // /facilities now has its own page.tsx — redirect removed
      // Phoenix TMS 404 fix
      { source: "/locations/phoenix-tms", destination: "/treatments/tms-therapy", permanent: true },
      { source: "/facilities/phoenix%20tms", destination: "/treatments/tms-therapy", permanent: true },
      { source: "/facilities/phoenix-tms", destination: "/treatments/tms-therapy", permanent: true },
      // SEO redirects — old program/treatment paths (updated destinations)
      { source: "/programs/residential", destination: "/levels-of-care/residential-treatment", permanent: true },
      { source: "/programs/residential/", destination: "/levels-of-care/residential-treatment", permanent: true },
      { source: "/programs/php", destination: "/treatments/php", permanent: true },
      { source: "/programs/php/", destination: "/treatments/php", permanent: true },
      { source: "/programs/iop", destination: "/treatments/iop", permanent: true },
      { source: "/programs/iop/", destination: "/treatments/iop", permanent: true },
      { source: "/treatment/iop", destination: "/treatments/iop", permanent: true },
      { source: "/treatment/iop/", destination: "/treatments/iop", permanent: true },
      { source: "/treatment/op", destination: "/treatments", permanent: true },
      { source: "/treatment/op/", destination: "/treatments", permanent: true },
      { source: "/treatment/family-program", destination: "/treatments", permanent: true },
      { source: "/treatment/family-program/", destination: "/treatments", permanent: true },
      // Resource page dead link redirects
      { source: "/resources/podcast", destination: "https://open.spotify.com/show/5thFT5DNC1exCkhmiug1Nb", permanent: false },
      { source: "/resources/what-to-pack", destination: "/resources/blog", permanent: false },
      { source: "/resources/family-guide", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/resources/signs-you-need-help", destination: "/resources/blog/gray-area-drinking-am-i-an-alcoholic", permanent: true },
      { source: "/resources/aftercare", destination: "/levels-of-care/residential-treatment", permanent: true },
      // SEO redirects — renamed content pages
      { source: "/addiction/understanding-gambling-addiction/", destination: "/addiction/gambling-addiction-treatment/", permanent: true },
      { source: "/addiction/understanding-sex-addiction/", destination: "/addiction/sex-addiction-treatment/", permanent: true },
      { source: "/treatments/alternative-therapy", destination: "/treatments/softwave-therapy", permanent: true }, // fix: was 404 (trailing slash on source caused slash-strip → bare → 404)
      { source: "/treatments/understanding-cbt-cognitive-behavioral-therapy/", destination: "/treatments/cbt-cognitive-behavioral-therapy", permanent: true }, // fix: was 404 (cognitive-behavioral-therapy-cbt route does not exist)
      { source: "/treatments/understanding-dbt-dialectic-behavior-therapy/", destination: "/treatments/dbt-dialectical-behavior-therapy", permanent: true }, // fix: was 404 (dialectical-behavior-therapy-dbt route does not exist)
      { source: "/treatments/emdr-eye-movement-desensitization-and-reprocessing", destination: "/treatments/emdr-therapy", permanent: true },
      { source: "/treatments/emdr-eye-movement-desensitization-and-reprocessing/", destination: "/treatments/emdr-therapy", permanent: true },
      // Insurance-verification consolidation (/get-help kept as standalone admissions page)
      { source: "/insurance-verification", destination: "/insurance", permanent: true },
      { source: "/insurance-verification/", destination: "/insurance", permanent: true },
      // Resource sub-pages removed in WP → Next migration
      { source: "/resources/access-webinars", destination: "/resources", permanent: true },
      { source: "/resources/access-webinars/", destination: "/resources", permanent: true },
      { source: "/resources/our-podcast", destination: "/resources", permanent: true },
      { source: "/resources/our-podcast/", destination: "/resources", permanent: true },
      // Google Ads landing page redirects
      { source: "/drug-alcohol-detox-lp", destination: "/levels-of-care/detox", permanent: true },
      { source: "/drug-alcohol-detox-lp/", destination: "/levels-of-care/detox", permanent: true },
      // Duplicate page cleanup
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/about-us/", destination: "/about", permanent: true },
      { source: "/addiction", destination: "/addiction-treatment", permanent: true },
      { source: "/addiction/", destination: "/addiction-treatment", permanent: true },
      { source: "/adolescent-program", destination: "/adolescent-treatment", permanent: true },
      { source: "/adolescent-program/", destination: "/adolescent-treatment", permanent: true },
      { source: "/facilities/glendale", destination: "/locations/glendale", permanent: true },
      { source: "/facilities/glendale/", destination: "/locations/glendale", permanent: true },
      { source: "/facilities/phoenix", destination: "/locations/phoenix-php-iop", permanent: true },
      { source: "/facilities/phoenix/", destination: "/locations/phoenix-php-iop", permanent: true },
      { source: "/facilities/scottsdale", destination: "/locations/scottsdale", permanent: true },
      { source: "/facilities/scottsdale/", destination: "/locations/scottsdale", permanent: true },
      { source: "/blog", destination: "/resources/blog", permanent: true },
      { source: "/blog/", destination: "/resources/blog", permanent: true },

      // === WordPress → Next.js cutover redirects (2026-04-25) ===
      // Source of truth: migration-audit/redirects-final.json (86 entries reviewed and approved)
      // Each entry generates two rules: with and without trailing slash, per existing convention.
      // CBT/DBT bug fix: existing entries above had 404 destinations; corrected in-place.
      // Skipped (already covered by existing entries above): /about-us, /insurance-verification,
      //   /resources/our-podcast, /treatments/emdr-eye-movement-desensitization-and-reprocessing,
      //   /blog (5 dedup pairs); /treatments/alternative-therapy (existing softwave wins).

      // --- Exact /blog/* → /resources/blog/* passthroughs (preserves SEO for ported posts) ---
      { source: "/blog/can-quitting-weed-cause-anxiety", destination: "/resources/blog/can-quitting-weed-cause-anxiety", permanent: true },
      { source: "/blog/can-quitting-weed-cause-anxiety/", destination: "/resources/blog/can-quitting-weed-cause-anxiety", permanent: true },
      { source: "/blog/do-drug-addicts-and-alcoholics-crave-dopamine", destination: "/resources/blog/do-drug-addicts-and-alcoholics-crave-dopamine", permanent: true },
      { source: "/blog/do-drug-addicts-and-alcoholics-crave-dopamine/", destination: "/resources/blog/do-drug-addicts-and-alcoholics-crave-dopamine", permanent: true },
      { source: "/blog/how-do-prescription-drugs-affect-your-brain", destination: "/resources/blog/how-do-prescription-drugs-affect-your-brain", permanent: true },
      { source: "/blog/how-do-prescription-drugs-affect-your-brain/", destination: "/resources/blog/how-do-prescription-drugs-affect-your-brain", permanent: true },
      { source: "/blog/how-does-an-addicts-brain-work", destination: "/resources/blog/how-does-an-addicts-brain-work", permanent: true },
      { source: "/blog/how-does-an-addicts-brain-work/", destination: "/resources/blog/how-does-an-addicts-brain-work", permanent: true },
      { source: "/blog/how-drug-and-alcohol-addiction-impacts-families", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-drug-and-alcohol-addiction-impacts-families/", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/is-addiction-a-spiritual-disease", destination: "/resources/blog/is-addiction-a-spiritual-disease", permanent: true },
      { source: "/blog/is-addiction-a-spiritual-disease/", destination: "/resources/blog/is-addiction-a-spiritual-disease", permanent: true },
      { source: "/blog/what-is-sex-addiction", destination: "/resources/blog/what-is-sex-addiction", permanent: true },
      { source: "/blog/what-is-sex-addiction/", destination: "/resources/blog/what-is-sex-addiction", permanent: true },

      // --- Cross-section + fuzzy /blog/* redirects (consolidates retired posts) ---
      { source: "/blog/are-mental-health-conditions-genetic", destination: "/resources/mental-health-assessment", permanent: true },
      { source: "/blog/are-mental-health-conditions-genetic/", destination: "/resources/mental-health-assessment", permanent: true },
      { source: "/blog/are-private-detox-centers-in-arizona-safer-than-public-ones", destination: "/levels-of-care/detox", permanent: true },
      { source: "/blog/are-private-detox-centers-in-arizona-safer-than-public-ones/", destination: "/levels-of-care/detox", permanent: true },
      { source: "/blog/can-alcohol-consumption-lead-to-depression", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/can-alcohol-consumption-lead-to-depression/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/can-reducing-alcohol-intake-improve-mental-health", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/can-reducing-alcohol-intake-improve-mental-health/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/depression-vs-sadness", destination: "/mental-health/depression-treatment", permanent: true },
      { source: "/blog/depression-vs-sadness/", destination: "/mental-health/depression-treatment", permanent: true },
      { source: "/blog/executive-burnout-and-addiction", destination: "/resources/blog/luxury-rehab-vs-standard-rehab-clinical-differences", permanent: true },
      { source: "/blog/executive-burnout-and-addiction/", destination: "/resources/blog/luxury-rehab-vs-standard-rehab-clinical-differences", permanent: true },
      { source: "/blog/how-do-alcohol-rehab-scottsdale-programs-differ-from-others", destination: "/locations/scottsdale", permanent: true },
      { source: "/blog/how-do-alcohol-rehab-scottsdale-programs-differ-from-others/", destination: "/locations/scottsdale", permanent: true },
      { source: "/blog/how-do-i-overcome-depression", destination: "/mental-health/depression-treatment", permanent: true },
      { source: "/blog/how-do-i-overcome-depression/", destination: "/mental-health/depression-treatment", permanent: true },
      { source: "/blog/how-do-you-explain-addiction-to-young-children-in-the-home", destination: "/adolescent-treatment", permanent: true },
      { source: "/blog/how-do-you-explain-addiction-to-young-children-in-the-home/", destination: "/adolescent-treatment", permanent: true },
      { source: "/blog/how-do-you-set-healthy-boundaries-with-an-addicted-loved-one-without-enabling", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-do-you-set-healthy-boundaries-with-an-addicted-loved-one-without-enabling/", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-does-addiction-affect-you-spiritually", destination: "/resources/blog/is-addiction-a-spiritual-disease", permanent: true },
      { source: "/blog/how-does-addiction-affect-you-spiritually/", destination: "/resources/blog/is-addiction-a-spiritual-disease", permanent: true },
      { source: "/blog/how-does-alcohol-abuse-impact-overall-mental-and-physical-health", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/how-does-alcohol-abuse-impact-overall-mental-and-physical-health/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/how-does-alcohol-affect-mental-health", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/how-does-alcohol-affect-mental-health/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/how-does-alcohol-affect-mental-health-2", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/how-does-alcohol-affect-mental-health-2/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/how-does-alcohol-affect-sleep", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/how-does-alcohol-affect-sleep/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/how-does-drug-and-alcohol-addiction-affect-families", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-does-drug-and-alcohol-addiction-affect-families/", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-does-therapy-help-with-codependency", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-does-therapy-help-with-codependency/", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-to-cope-with-ptsd-triggers", destination: "/mental-health/ptsd-treatment", permanent: true },
      { source: "/blog/how-to-cope-with-ptsd-triggers/", destination: "/mental-health/ptsd-treatment", permanent: true },
      { source: "/blog/how-to-help-a-loved-one-get-into-long-term-inpatient-treatment", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/blog/how-to-help-a-loved-one-get-into-long-term-inpatient-treatment/", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/blog/how-to-help-an-alcoholic-or-addict-who-doesnt-want-help", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/blog/how-to-help-an-alcoholic-or-addict-who-doesnt-want-help/", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/blog/how-to-help-someone-with-mental-health-issues", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/blog/how-to-help-someone-with-mental-health-issues/", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/blog/how-to-rewire-the-brain-from-addiction", destination: "/resources/blog/how-does-an-addicts-brain-work", permanent: true },
      { source: "/blog/how-to-rewire-the-brain-from-addiction/", destination: "/resources/blog/how-does-an-addicts-brain-work", permanent: true },
      { source: "/blog/how-to-stop-being-codependent-with-an-addict-or-alcoholic", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-to-stop-being-codependent-with-an-addict-or-alcoholic/", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/how-to-tell-if-my-son-or-daughter-needs-addiction-treatment-or-mental-health-treatment", destination: "/adolescent-treatment", permanent: true },
      { source: "/blog/how-to-tell-if-my-son-or-daughter-needs-addiction-treatment-or-mental-health-treatment/", destination: "/adolescent-treatment", permanent: true },
      { source: "/blog/is-depression-a-disease", destination: "/mental-health/depression-treatment", permanent: true },
      { source: "/blog/is-depression-a-disease/", destination: "/mental-health/depression-treatment", permanent: true },
      { source: "/blog/is-there-a-link-between-alcohol-use-and-suicide-risk", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/is-there-a-link-between-alcohol-use-and-suicide-risk/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/long-term-clinical-care-vs-short-term-clinical-care-with-addiction-and-mental-health", destination: "/levels-of-care/residential-treatment", permanent: true },
      { source: "/blog/long-term-clinical-care-vs-short-term-clinical-care-with-addiction-and-mental-health/", destination: "/levels-of-care/residential-treatment", permanent: true },
      { source: "/blog/team-group/clinical-staff", destination: "/our-team", permanent: true },
      { source: "/blog/team-group/clinical-staff/", destination: "/our-team", permanent: true },
      { source: "/blog/team-group/leadership", destination: "/our-team", permanent: true },
      { source: "/blog/team-group/leadership/", destination: "/our-team", permanent: true },
      { source: "/blog/understanding-the-risks-of-drug-or-alcohol-detox-and-why-you-need-a-professional", destination: "/resources/blog/risks-of-drug-or-alcohol-detox-why-you-need-professional-help", permanent: true },
      { source: "/blog/understanding-the-risks-of-drug-or-alcohol-detox-and-why-you-need-a-professional/", destination: "/resources/blog/risks-of-drug-or-alcohol-detox-why-you-need-professional-help", permanent: true },
      { source: "/blog/what-are-the-long-term-mental-health-effects-of-chronic-alcohol-use", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/what-are-the-long-term-mental-health-effects-of-chronic-alcohol-use/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/blog/what-are-the-signs-of-detoxing-from-alcohol", destination: "/resources/blog/risks-of-drug-or-alcohol-detox-why-you-need-professional-help", permanent: true },
      { source: "/blog/what-are-the-signs-of-detoxing-from-alcohol/", destination: "/resources/blog/risks-of-drug-or-alcohol-detox-why-you-need-professional-help", permanent: true },
      { source: "/blog/what-are-the-stages-of-family-recovery", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/what-are-the-stages-of-family-recovery/", destination: "/resources/blog/how-drug-and-alcohol-addiction-impacts-families", permanent: true },
      { source: "/blog/what-are-the-top-holistic-therapies-for-addiction-and-mental-health", destination: "/resources/blog/why-holistic-treatment-is-required-for-long-term-recovery", permanent: true },
      { source: "/blog/what-are-the-top-holistic-therapies-for-addiction-and-mental-health/", destination: "/resources/blog/why-holistic-treatment-is-required-for-long-term-recovery", permanent: true },
      { source: "/blog/what-are-the-top-holistic-therapies-for-addiction-and-mental-health-2", destination: "/resources/blog/why-holistic-treatment-is-required-for-long-term-recovery", permanent: true },
      { source: "/blog/what-are-the-top-holistic-therapies-for-addiction-and-mental-health-2/", destination: "/resources/blog/why-holistic-treatment-is-required-for-long-term-recovery", permanent: true },
      { source: "/blog/what-is-cognitive-behavioral-therapy", destination: "/treatments/cbt-cognitive-behavioral-therapy", permanent: true },
      { source: "/blog/what-is-cognitive-behavioral-therapy/", destination: "/treatments/cbt-cognitive-behavioral-therapy", permanent: true },
      { source: "/blog/what-is-gray-area-drinking", destination: "/resources/blog/gray-area-drinking-am-i-an-alcoholic", permanent: true },
      { source: "/blog/what-is-gray-area-drinking/", destination: "/resources/blog/gray-area-drinking-am-i-an-alcoholic", permanent: true },
      { source: "/blog/what-is-holistic-treatment", destination: "/resources/blog/why-holistic-treatment-is-required-for-long-term-recovery", permanent: true },
      { source: "/blog/what-is-holistic-treatment/", destination: "/resources/blog/why-holistic-treatment-is-required-for-long-term-recovery", permanent: true },
      { source: "/blog/what-is-trauma-focused-cognitive-behavioral-therapy", destination: "/treatments/cbt-cognitive-behavioral-therapy", permanent: true },
      { source: "/blog/what-is-trauma-focused-cognitive-behavioral-therapy/", destination: "/treatments/cbt-cognitive-behavioral-therapy", permanent: true },
      { source: "/blog/what-makes-a-luxury-rehab-near-me-worth-it", destination: "/resources/blog/luxury-rehab-vs-standard-rehab-clinical-differences", permanent: true },
      { source: "/blog/what-makes-a-luxury-rehab-near-me-worth-it/", destination: "/resources/blog/luxury-rehab-vs-standard-rehab-clinical-differences", permanent: true },
      { source: "/blog/what-should-you-expect-at-an-inpatient-drug-rehab-facility-in-arizona", destination: "/levels-of-care/residential-treatment", permanent: true },
      { source: "/blog/what-should-you-expect-at-an-inpatient-drug-rehab-facility-in-arizona/", destination: "/levels-of-care/residential-treatment", permanent: true },
      { source: "/blog/what-to-say-to-someone-struggling-with-a-mental-health-disorder", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/blog/what-to-say-to-someone-struggling-with-a-mental-health-disorder/", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/blog/what-types-of-clinical-therapies-are-offered-during-residential-treatment", destination: "/levels-of-care/residential-treatment", permanent: true },
      { source: "/blog/what-types-of-clinical-therapies-are-offered-during-residential-treatment/", destination: "/levels-of-care/residential-treatment", permanent: true },
      { source: "/blog/why-do-professionals-often-need-specialized-treatment-programs", destination: "/resources/blog/luxury-rehab-vs-standard-rehab-clinical-differences", permanent: true },
      { source: "/blog/why-do-professionals-often-need-specialized-treatment-programs/", destination: "/resources/blog/luxury-rehab-vs-standard-rehab-clinical-differences", permanent: true },
      { source: "/blog/why-does-a-smaller-boutique-program-often-lead-to-better-outcomes-than-large-corporate-rehabs", destination: "/resources/blog/luxury-rehab-vs-standard-rehab-clinical-differences", permanent: true },
      { source: "/blog/why-does-a-smaller-boutique-program-often-lead-to-better-outcomes-than-large-corporate-rehabs/", destination: "/resources/blog/luxury-rehab-vs-standard-rehab-clinical-differences", permanent: true },
      { source: "/blog/why-holistic-treatment-is-required-for-long-term-recovery-success", destination: "/resources/blog/why-holistic-treatment-is-required-for-long-term-recovery", permanent: true },
      { source: "/blog/why-holistic-treatment-is-required-for-long-term-recovery-success/", destination: "/resources/blog/why-holistic-treatment-is-required-for-long-term-recovery", permanent: true },
      { source: "/blog/wpautoterms", destination: "/privacy-policy", permanent: true },
      { source: "/blog/wpautoterms/", destination: "/privacy-policy", permanent: true },

      // --- Non-blog cutover redirects ---
      { source: "/learning", destination: "/resources", permanent: true },
      { source: "/learning/", destination: "/resources", permanent: true },
      { source: "/linktree", destination: "/", permanent: true },
      { source: "/linktree/", destination: "/", permanent: true },
      { source: "/resources/addiction-detox-guide", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/adderall", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/adderall/", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/alcohol", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/alcohol/", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/benzodiazepines", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/benzodiazepines/", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/fentanyl", destination: "/resources/detox-guide", permanent: true },
      { source: "/resources/addiction-detox-guide/fentanyl/", destination: "/resources/detox-guide", permanent: true },
      { source: "/start-your-road-to-recovery", destination: "/get-help", permanent: true },
      { source: "/start-your-road-to-recovery/", destination: "/get-help", permanent: true },
      { source: "/treatments/holistic-therapies/art", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/art/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/biofeedback-and-neurofeedback", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/biofeedback-and-neurofeedback/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/breathwork", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/breathwork/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/guided-meditation", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/guided-meditation/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/massage", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/massage/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/mindfulness-based-relapse-prevention", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/mindfulness-based-relapse-prevention/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/mindfulness-based-stress-reduction", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/mindfulness-based-stress-reduction/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/music-therapy", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/music-therapy/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/nutrition", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/nutrition/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/transcendental-meditation", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/transcendental-meditation/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/yoga", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/treatments/holistic-therapies/yoga/", destination: "/treatments/holistic-therapies", permanent: true },
      { source: "/webinar/how-do-prescription-drugs-affect-your-brain", destination: "/resources/blog/how-do-prescription-drugs-affect-your-brain", permanent: true },
      { source: "/webinar/how-do-prescription-drugs-affect-your-brain/", destination: "/resources/blog/how-do-prescription-drugs-affect-your-brain", permanent: true },
      { source: "/webinar/how-does-alcohol-affect-mental-health", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/webinar/how-does-alcohol-affect-mental-health/", destination: "/resources/blog/how-does-alcohol-abuse-impact-mental-and-physical-health", permanent: true },
      { source: "/webinar/what-to-say-to-someone-with-a-mental-health-disorder", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },
      { source: "/webinar/what-to-say-to-someone-with-a-mental-health-disorder/", destination: "/resources/blog/how-to-talk-to-someone-about-going-to-rehab", permanent: true },

      // --- Non-trailing-slash variants (trailing-slash counterparts handled by existing entries above) ---
      { source: "/addiction/understanding-gambling-addiction", destination: "/addiction/gambling-addiction-treatment", permanent: true },
      { source: "/addiction/understanding-sex-addiction", destination: "/addiction/sex-addiction-treatment", permanent: true },
      { source: "/treatments/understanding-cbt-cognitive-behavioral-therapy", destination: "/treatments/cbt-cognitive-behavioral-therapy", permanent: true },
      { source: "/treatments/understanding-dbt-dialectic-behavior-therapy", destination: "/treatments/dbt-dialectical-behavior-therapy", permanent: true },
    ];
  },
};

export default nextConfig;
